### PR TITLE
Debianized

### PR DESCRIPTION
**Pull request by xaionaro**

### CODE REVIEW

**Comment by buhtz** [comment]
I would like to test the deb-file on my Debian unstable  (64bit) if someone could build it.

**Comment by jekader** [comment]
I already merged code for debian packaging a few years ago as #156
Could you please merge your changes on top of that code in the packaging directory if you think this is still needed?

**Comment by xaionaro** [comment]
Ok, sorry. Usually directory "debian/" is on the top.

**Comment by xaionaro** [comment]
Well, my packaging works for me. @jekader, yours -- doesn't :(
```
cd qmltermwidget/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /tmp/cool-retro-term/qmltermwidget/qmltermwidget.pro -nocache 'QMAKE_CFLAGS_RELEASE=-g -O2 ' 'QMAKE_CFLAGS_DEBUG=-g -O2 ' 'QMAKE_CXXFLAGS_RELEASE=-g -O2 ' 'QMAKE_CXXFLAGS_DEBUG=-g -O2 ' QMAKE_STRIP=: PREFIX=/usr -o Makefile ) && make -f Makefile 
Cannot find file: /tmp/cool-retro-term/qmltermwidget/qmltermwidget.pro.
Makefile:43: recipe for target 'sub-qmltermwidget-make_first-ordered' failed
```

**Comment by xaionaro** [comment]
On the other hand, never mind... No time to recheck everything right. Sorry.

**Comment by buhtz** [comment]
And now can someone provide a deb-file?

**Comment by xtaran** [comment]
On Wed, Feb 01, 2017 at 12:51:32AM -0800, Okunev Yu Dmitry wrote:
> Ok, sorry.

No need to be sorry.

> Usually directory "debian/" is on the top.

Exactly. And if it's anywhere else, don't expect people to find it as
Debian's tools _only_ expect the "debian/" directory on top-level and
won't work if it's not on top-level.

**Comment by xaionaro** [comment]
> And now can someone provide a deb-file?

Here's files just built for debian/sid:

[ftp://mirror.mephi.ru/other/2017/cool-retro-term-sid/](ftp://mirror.mephi.ru/other/2017/cool-retro-term-sid/)

**Comment by buhtz** [comment]
Yes it is working! :D

**Pull request closed without merging**
