### PR TITLE
SNAP for cool-retro-term

### PR DESCRIPTION
**Pull request by kz6fittycent**
This yaml will allow the project to create a snap for c-r-t and allow distribution to any Linux distro running snapd. 

The snap NEEDS "classic" confinement to run properly.

### CODE REVIEW

**Comment by LeonB** [comment]
I get this error when building the snap and then running it:

```
$ cool-retro-term
/snap/cool-retro-term/x1/command-cool-retro-term.wrapper: 2: exec: desktop-launch: not found
```

I fixed it by using adding this to the snapcraft.yaml:

``` yml
    command: bin/desktop-launch $SNAP/usr/bin/cool-retro-term
```

**Comment by kz6fittycent** [comment]
were you building it locally? If so, there's already a snap available for download and it works on multiple distros.

`sudo snap install --devmode --edge cool-retro-term`

**Comment by kz6fittycent** [comment]
Touching base with you again regarding --classic confinement. Snapcrafters are awaiting your approval before it happens. 

The snap "would" make things easier for the project to distribute the application across all* the distros.

**Comment by Swordfish90** [comment]
Sorry for the very very long wait... I guess we can close this one...

**Pull request closed without merging**
