### PR TITLE
Create cool-retro-term_install_debian.sh

### PR DESCRIPTION
**Pull request by CodeLongAndProsper90**
Make a shell script to automate compiling from source

### CODE REVIEW

**Comment by alexmyczko** [comment]
would it not be easier if you could run `apt install cool-retro-term` instead?

**Comment by CodeLongAndProsper90** [comment]
At least for me, I cannot use the ppa, so I have to build from source.
One alternative would to make a stand-alone cool-retro-term.deb file, so you could run 
```
sudo apt install ./cool-retro-term.deb
```

**Comment by alexmyczko** [comment]
i did not have ppa in mind but official repos

**Comment by CodeLongAndProsper90** [comment]
I know, but that requires that we:
A. Make a deb file
B. Get it uploaded into debian-main

**Comment by alexmyczko** [comment]
https://packages.debian.org/cool-retro-term

**Comment by CodeLongAndProsper90** [comment]
Well, that simplifies things.

**Pull request closed without merging**
