### PR TITLE
Generate AppImage of each build on Travis CI

### PR DESCRIPTION
**Pull request by probonopd**
As per https://github.com/Swordfish90/cool-retro-term/issues/136#issuecomment-255710968.

__Download link will be in the Travis CI build log.__

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

### CODE REVIEW

**Comment by probonopd** [comment]
Ping, is anything preventing this from being merged?

**Comment by probonopd** [comment]
Pinging once more, now that 1.0 is there...

**Comment by Swordfish90** [comment]
Ok. Thank you very much for this. Sorry it took so long for merging it.

**Comment by Swordfish90** [comment]
Something seems to be broken with qt versions: https://travis-ci.org/Swordfish90/cool-retro-term/jobs/474627956

**Pull request merged**
